int numTes = 0, score = 0;
String tesName = "";

List soalJawaban = [
  [
    [
      "What is 3 × 2 as repeated addition?",
      "3 + 2",
      "2 + 2 + 2",
      "3 + 3 + 3",
      "2 + 3 + 2",
      "2 + 2 + 2",
    ],
    ["What is the product of 4 × 5?", "10", "15", "20", "25", "20"],
    [
      "In 6 × 2 = 12, what are the factors?",
      "6 and 2",
      "6 and 12",
      "2 and 12",
      "12 and 1",
      "6 and 2",
    ],
    [
      "What is 5 + 5 + 5 the same as?",
      "5 × 2",
      "5 × 4",
      "5 × 3",
      "3 × 2",
      "5 × 3",
    ],
    [
      "Which of these is equal to 3 × 4 using the commutative property?",
      "4 × 3",
      "3 + 4",
      "4 + 3 + 4",
      "3 + 3 + 4",
      "4 × 3",
    ],
    ["What is the product of 2 × 6?", "8", "10", "12", "14", "12"],
    ["How many times is 3 added in 3 × 4?", "3", "2", "4", "1", "4"],
    [
      "Which multiplication sentence equals 16?",
      "4 × 5",
      "2 × 6",
      "8 × 2",
      "3 × 4",
      "8 × 2",
    ],
    ["In 7 × 1 = 7, which number is the product?", "1", "7", "0", "8", "7"],
    [
      "Which of these is NOT equal to 6 × 2?",
      "2 × 6",
      "6 + 6",
      "2 + 2 + 2",
      "3 × 4",
      "2 + 2 + 2",
    ],
    10,
  ],
  [
    [
      "What does the word 'reptile' come from?",
      "A Greek word for 'swim'",
      "A Latin word for 'fly'",
      "A Latin word for 'crawl'",
      "An Egyptian word for 'run'",
      "A Latin word for 'crawl'",
    ],
    [
      "How do most reptiles move?",
      "By flying",
      "By crawling close to the ground",
      "By jumping",
      "By swimming only",
      "By crawling close to the ground",
    ],
    [
      "Which of the following is a main characteristic of reptiles?",
      "They are warm-blooded",
      "They lay eggs",
      "They have feathers",
      "They live only in water",
      "They lay eggs",
    ],
    [
      "What covers the body of most reptiles?",
      "Fur",
      "Feathers",
      "Slimy skin",
      "Tough scales",
      "Tough scales",
    ],
    [
      "Which of the following reptiles has a protective shell?",
      "Lizard",
      "Snake",
      "Tortoise",
      "Crocodile",
      "Tortoise",
    ],
    [
      "What kind of blood do reptiles have?",
      "Cold-blooded",
      "Hot-blooded",
      "Mixed-blooded",
      "Frozen-blooded",
      "Cold-blooded",
    ],
    [
      "What do most reptiles eat?",
      "Fruits only",
      "Meat",
      "Grass only",
      "Bread",
      "Meat",
    ],
    [
      "What is one way reptiles protect themselves?",
      "Hiding under water",
      "Using venom",
      "Flying away",
      "Digging deep holes",
      "Using venom",
    ],
    [
      "Which reptile uses camouflage to hide?",
      "Turtle",
      "Snake",
      "Chameleon",
      "Alligator",
      "Chameleon",
    ],
    [
      "Why do some reptiles have bright colors?",
      "To look pretty",
      "To attract bugs",
      "To warn other animals",
      "To make fire",
      "To warn other animals",
    ],
    10,
  ],
  [
    [
      "Where was Cleopatra born?",
      "Rome",
      "Thebes",
      "Alexandria",
      "Athens",
      "Alexandria",
    ],
    [
      "How old was Cleopatra when she became queen?",
      "16",
      "18",
      "20",
      "25",
      "18",
    ],
    [
      "Which of the following did Cleopatra study?",
      "Only history",
      "Only music and art",
      "Math, philosophy, and more",
      "Only medicine",
      "Math, philosophy, and more",
    ],
    [
      "How many languages did Cleopatra speak?",
      "Three",
      "Five",
      "Seven",
      "Nine",
      "Nine",
    ],
    [
      "Which subject was NOT mentioned as something Cleopatra studied?",
      "Philosophy",
      "Astronomy",
      "Engineering",
      "Medicine",
      "Engineering",
    ],
    [
      "Why was it unusual for Cleopatra to become ruler?",
      "She was too young",
      "She was not from Egypt",
      "She was a woman",
      "She didn’t go to school",
      "She was a woman",
    ],
    [
      "What happened to Cleopatra after she had problems with her brother?",
      "She became a general",
      "She was made a princess",
      "She was expelled from Egypt",
      "She became a singer",
      "She was expelled from Egypt",
    ],
    [
      "Who did Cleopatra get help from after being betrayed by her brother?",
      "Alexander the Great",
      "Julius Caesar",
      "Socrates",
      "Leonardo da Vinci",
      "Julius Caesar",
    ],
    [
      "Why did Cleopatra form an alliance with Julius Caesar?",
      "To learn more languages",
      "To defeat Rome",
      "To help her become queen again",
      "To move to Italy",
      "To help her become queen again",
    ],
    [
      "Which skill helped Cleopatra become a strong leader?",
      "Being very tall",
      "Being great at dancing",
      "Being well-educated",
      "Owning many pets",
      "Being well-educated",
    ],
    10,
  ],
];
